### ISSUE TITLE
add a parameter for 4k screens

### ISSUE THREAD

**Issue by toccata10** [edisionnano/Pine-jinx#1]
Thanks for this easy to use tool.
As I have a 4k screen, I suggest you add an option to add this parameter in the alias
GDK_DPI_SCALE=0.5
My screenshots don't show the difference too well, but the 1st one (without GDK_DPI_SCALE=0.5) has really big fonts
![image](https://user-images.githubusercontent.com/7478580/124711436-5db2f200-defe-11eb-9128-189032bdbf52.png)
With GDK_DPI_SCALE=0.5: much better display:
![image](https://user-images.githubusercontent.com/7478580/124711466-67d4f080-defe-11eb-9613-ee568550070a.png)

**Comment by edisionnano** [comment]
Ryujinx will deprecate GTK in favor of Avalonja Ui, I suggest that we wait.

**Comment by toccata10** [comment]
Sure. Thanks.
