### ISSUE TITLE
force_integer_tex_nearest=true needed for Kirby All Stars

### ISSUE THREAD

**Issue by toccata10** [edisionnano/Pine-jinx#2]
With force_integer_tex_nearest=true Kirby games render correctly on Amd (r9 fury):
![20210707_093317](https://user-images.githubusercontent.com/7478580/124718735-b1293e00-df06-11eb-886d-c1c77e10fe36.jpg)
Without it, there's a problem:
![20210707_093319](https://user-images.githubusercontent.com/7478580/124718745-b38b9800-df06-11eb-88ba-d37944a931a1.jpg)

I don't know how setting this parameter all the time affects the performance for other ryujinx games (I didn't see any difference while testing a few games, but I didn't conduct a very long experimentation on this).

**Comment by edisionnano** [comment]
Added! Big thanks, how did you find this one?

**Comment by toccata10** [comment]
There was a guy name "johngalt" on yuzu's discord server a while ago. He looked like a linux guru. He taught me many things, this trick for example. Sadly, suddendly, he disappeared.
